### ISSUE TITLE
New notification and new commands

### ISSUE THREAD

**Issue by Cyberillc** [liebki/SimplePushEvents#2]
Add player death notification and add a command to chat with other on ntfy.sh and get chat messages from people on ntfy.sh

**Comment by liebki** [comment]
@Cyberillc player death etc. all events are not a problem. The chat command 
is okay too, like to send push messages using /spe (message). I don't want to add a receive function right now, I don't see a good way to chat from ntfy.sh to a server.

I will add it as a next update to allow communication between multiple servers, like a global chat featured by ntfy.sh or just to message players from server to server.

Maybe I will use the MQTT protocol for this feature, idk yet. (maybe I'll create a separate plugin for that feature tho).

EDIT
